name: Release

on:
  push:
    paths:
      - '.changeset/**'
      - 'src/**'
    branches:
      - main
      - next
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Cache node modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: pnpm-deps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-deps-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build addon
        run: pnpm build

      - name: Install Playwright Chromium
        run: pnpm exec playwright install chromium --with-deps

      - name: Test addon
        run: pnpm test

      - name: E2E tests
        run: pnpm test:e2e

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changesets): version packages'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog
        if: steps.changesets.outputs.published == 'true'
        run: |
          pnpm changelog:latest
          pnpm changelog:format
          pnpm changelog:commit
